// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF7d2qXXb8npPqU-gYPQ5rOvpIKaa7-Lw',
    appId: '1:341183990697:web:21e19203af4b17778b52b8',
    messagingSenderId: '341183990697',
    projectId: 'app-movil-acbfa',
    authDomain: 'app-movil-acbfa.firebaseapp.com',
    databaseURL: 'https://app-movil-acbfa-default-rtdb.firebaseio.com',
    storageBucket: 'app-movil-acbfa.appspot.com',
    measurementId: 'G-KX3CTRBJ4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Lfd3-lXTpR3L3Ajd6-EN3nyMgd97Nwc',
    appId: '1:341183990697:android:2f07507f608f88d28b52b8',
    messagingSenderId: '341183990697',
    projectId: 'app-movil-acbfa',
    databaseURL: 'https://app-movil-acbfa-default-rtdb.firebaseio.com',
    storageBucket: 'app-movil-acbfa.appspot.com',
  );
}
